apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oast9ssa4-python 
  janus-idp.io/tekton: oast9ssa4-python
  backstage.io/kubernetes-id: oast9ssa4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oast9ssa4-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml