apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oast9ssa4-python
  janus-idp.io/tekton: oast9ssa4-python
  backstage.io/kubernetes-id: oast9ssa4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oast9ssa4-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
